### ISSUE TITLE
Some strings are not extracted even after upgrading to 5.2.0

### ISSUE THREAD

**Issue by progmatic-99** [Cropster/ember-l10n#101]
Strings were not being extracted with ```v4.1.3``` and after upgrade they are still not being extracted

See [this](https://github.com/fossasia/open-event-frontend/issues/7937)

@mydea Can you help as this is a priority issue as most of our customers are non-English speakers??

Thanks a lot!!

**Comment by mydea** [comment]
Can you provide more information? What strings are not being extracted, for example? If you can provide some code that is not properly extracted I can look into it.

**Comment by progmatic-99** [comment]
+ All the name fields in `columns()` [here](https://github.com/progmatic-99/open-event-frontend/blob/892cb614a229182f40713318f8e584e911a9b3fc/app/controllers/account/billing/invoices/list.js#L10) 
+ [this](https://github.com/progmatic-99/open-event-frontend/blob/d464e5a5eb6c9a5be2b5e564cd820f71f9373635/app/templates/components/events/view/overview/general-info.hbs#L19) and [here](https://github.com/progmatic-99/open-event-frontend/blob/892cb614a229182f40713318f8e584e911a9b3fc/app/templates/components/events/view/overview/general-info.hbs#L32)
+ [this](https://github.com/progmatic-99/open-event-frontend/blob/d464e5a5eb6c9a5be2b5e564cd820f71f9373635/app/templates/components/forms/group/group-settings-form.hbs#L41) 
+ [this](https://github.com/progmatic-99/open-event-frontend/blob/892cb614a229182f40713318f8e584e911a9b3fc/app/templates/components/forms/orders/order-form.hbs#L14)
+ [also this](https://github.com/progmatic-99/open-event-frontend/blob/892cb614a229182f40713318f8e584e911a9b3fc/app/templates/events/view/chat.hbs#L13)
+ [this](https://github.com/progmatic-99/open-event-frontend/blob/892cb614a229182f40713318f8e584e911a9b3fc/app/templates/events/view/documents.hbs#L13)

**Comment by progmatic-99** [comment]
@mydea Thanks

**Comment by mydea** [comment]
I don't understand the problem, I think?

When I run `ember l10n:extract` on this branch: https://github.com/progmatic-99/open-event-frontend/tree/translation, I can see that these things are correctly picked up, as far as I can tell.

**Comment by progmatic-99** [comment]
We have a [script](https://github.com/fossasia/open-event-frontend/blob/development/scripts/l10n.js) that runs when we run `yarn l10n:extract`. See the command [here](https://github.com/fossasia/open-event-frontend/blob/9726f218283134771d8613dddf004996480d953b/package.json#L21)
This won't be needed anymore, ig???

**Comment by mydea** [comment]
I would recommend just using `ember l10n:extract` to extract strings. This will generally work and extract all strings and update the en.po & messages.pot file correctly. Not sure what happens in that script of yours. You can just do this in your package.json:

```json
"scripts": {
  "l10n:extract": "ember l10n:extract"
}
```

You should also generally not need the generate stuff, just run extract and it should be fine.
