### ISSUE TITLE
When generating, create default locales dir + en.json

### ISSUE THREAD

**Issue by Ramblurr** [Cropster/ember-l10n#11]
When installing ember-l10n on a fresh project, it creates the service which references /assets/locales and en.json, both of which probably don't exist.

It would be nice if the blueprint could create this directory and add a skeleton en.json file.

**Comment by arm1n** [comment]
Fixed with version [v1.0.0](https://github.com/Cropster/ember-l10n/releases/tag/v1.0.0).
