### ISSUE TITLE
l10n:extract throws error and stops

### ISSUE THREAD

**Issue by tadmore** [Cropster/ember-l10n#18]
After following the README info (installing, etc), running *extract* fails and generates an error.
```
ember install ember-l10n 👍
ember g ember-l10n-initializer my-l10n-initializer 👍
```
Used a single helper `{{t 'project'}}` as a first test, then ran *extract*
```
ember l10n:extract
find: no such file or directory: node_modules/make-array/addon/**/*.js 🚨
```

This looks like a great addon... excited to use it.

**Comment by mydea** [comment]
What is your OS/Environment?
Does it work with the `skip-all-dependencies` flag: `ember l10n:extract --skip-all-dependencies=true`?

**Comment by tadmore** [comment]
`skip-all-dependencies` works great.   It failed at the end because the *translations* directory didn't exist (yet), but that's easily fixable.  Once the dir was created it runs perfectly.

I'm running 
- macOS Sierra 10.12.6 (latest)
- Ember-cli v2.14.1
- Node v6.7.0

Thanks, this is great!

**Comment by arm1n** [comment]
Closing as resolved - generating the default file structure is already captured in #11.
