### ISSUE TITLE
Destructuring of `Ember.testing` will not work. 

### ISSUE THREAD

**Issue by rwjblue** [Cropster/ember-l10n#21]
`Ember.testing` is a getter/setter in Ember, and destructuring like this will only read its value at the time the module is evaluated. In this case, `Ember.testing` will most likely be `false` when the module is evaluated, then change to `true` _during_ the test. This behavior somewhat recently changed in https://github.com/emberjs/ember-test-helpers/pull/227 (which is included in `ember-cli-qunit@4.1.0` / `ember-qunit@3.0.0`).

I believe the fix here would be to remove the destructuring, and use `Ember.testing` directly inline.

https://github.com/Cropster/ember-l10n/blob/256eb162d80f86c88c61bfea93623ba97dff7ffe/addon/services/l10n.js#L4-L17

https://github.com/Cropster/ember-l10n/blob/256eb162d80f86c88c61bfea93623ba97dff7ffe/addon/services/l10n.js#L536-L538

**Comment by arm1n** [comment]
Thanks a lot for this hint, we're currently working on version `1.0.0` using latest Ember with new modules API and hope to have `import { isTesting, setTesting } from '@ember/test'` available as soon as possible (https://github.com/ember-cli/ember-rfc176-data/issues/12), then this issue should be gone anyways.

**Comment by mydea** [comment]
This is not used anymore, so I'm closing this!
