### ISSUE TITLE
Newslines and HTML in translations

### ISSUE THREAD

**Issue by Znegl** [Cropster/ember-l10n#33]
When adding newlines or HTML to my translations they seem to be ignored.
I've tried adding `unescapeText=true` to the helper `{{t 'My \n string with <br> newlines' unescapeText=true}}` but both the `\n` and `<br>` are printed out as plain text.
Trying to pass the result of `t()` through a helper for converting `\n` to `<br>` isn't possible either, since it is being escaped by the translation function.

**Comment by mydea** [comment]
Newlines will be ignored, but you can add any HTML tag you want by using triple curlies to deactivate the auto-escaping:

```hbs
{{{t 'This is <strong>bold</strong>'}}}
```
