### ISSUE TITLE
2.0.5 isn't on NPM

### ISSUE THREAD

**Issue by Znegl** [Cropster/ember-l10n#34]
It seems like version 2.0.5 isn't available on NPM. (https://www.npmjs.com/package/ember-l10n)
I guess it's just a matter of running `npm publish`

**Comment by arm1n** [comment]
Hey thanks for reporting this issue - you were right, the publish didn't make it onto the registry. Just have published it, should be available soon.

**Comment by Znegl** [comment]
Great, thanks!
