### ISSUE TITLE
Implement exists() function

### ISSUE THREAD

**Issue by mydea** [Cropster/ember-l10n#6]
In order to achieve maximal compatibility with ember-i18n and make migration as easy as possible, I propose that we add a `l10n.exists(key)` function. Basically, this function should return true if the given key exists for the currently set locale, else false.

Concretely, this is used by https://github.com/jasonmit/ember-i18n-cp-validations/blob/master/addon/initialize.js, which I am porting over for ember-l10n. It's not super important, but I guess it would be nice and an easy addition. If that makes sense, I'll make a PR?

**Comment by arm1n** [comment]
Sounds good for me. Please also add the method in [service's utility methods in README](https://github.com/Cropster/ember-l10n#service) as long as we have no proper JSDOC from sources - thanks!
